#!/usr/bin/env bash
# Displays DNS information about subdomains

show_info() {
    local sub="$1"
    local domain="$2"
    
    # Query dig for the answer section and extract record type and destination IP/target using awk
    local res
    res=$(dig "${sub}.${domain}" | awk '/^'"${sub}.${domain}"'\./ {print $4, $5}')
    
    local record_type
    record_type=$(echo "$res" | awk '{print $1}')
    
    local destination
    destination=$(echo "$res" | awk '{print $2}')

    echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
}

if [ "$#" -eq 2 ]; then
    show_info "$2" "$1"
else
    show_info "www" "$1"
    show_info "lb-01" "$1"
    show_info "web-01" "$1"
    show_info "web-02" "$1"
fi
